// Generated by scripts/generate-keypair.mjs. Public key only — safe to ship in the package.
export const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAZv2dAf0X+hk0kyP3vxyGVJAEno7n3KjlIO7vM7TERh8=
-----END PUBLIC KEY-----`;
