#!/usr/bin/env node
/**
 * One-time setup: generates the Ed25519 keypair used to sign/verify license
 * keys. The private key MUST stay secret (back it up, never commit it) —
 * anyone with it can mint valid licenses. The public key is written into
 * src/license/publicKey.ts and is safe to ship inside the npm package.
 */
import { generateKeyPairSync } from "crypto";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const root = process.cwd();
const keysDir = join(root, "keys");
const privPath = join(keysDir, "private.pem");
const publicKeyTsPath = join(root, "src/license/publicKey.ts");

if (existsSync(privPath)) {
  console.error(`Refusing to overwrite existing ${privPath}.`);
  console.error("Delete it first only if you understand this will invalidate every license key issued with it.");
  process.exit(1);
}

mkdirSync(keysDir, { recursive: true });

const { publicKey, privateKey } = generateKeyPairSync("ed25519");

writeFileSync(privPath, privateKey.export({ type: "pkcs8", format: "pem" }), "utf8");

const publicPem = publicKey.export({ type: "spki", format: "pem" }).toString().trim();
const tsContent =
  "// Generated by scripts/generate-keypair.mjs. Public key only — safe to ship in the package.\n" +
  "export const PUBLIC_KEY_PEM = `" + publicPem + "`;\n";

writeFileSync(publicKeyTsPath, tsContent, "utf8");

console.log(`Wrote private key: ${privPath}  (KEEP SECRET — back it up, do not commit)`);
console.log(`Wrote public key:  ${publicKeyTsPath}  (safe to ship)`);
console.log('\nNext: npm run build, then issue a key with:');
console.log('  npm run license:generate -- --email customer@example.com --tier pro');
